# Generated by Django 4.2.4 on 2023-09-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_alunos_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='turma',
            field=models.IntegerField(),
        ),
    ]
