# Generated by Django 4.2.4 on 2023-09-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia_aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='data',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='id_aluno',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='id_turma',
        ),
        migrations.RemoveField(
            model_name='frequencia',
            name='obs',
        ),
    ]
