# Generated by Django 4.2.4 on 2023-09-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0003_dia_aula_data_dia_aula_id_turma_frequencia_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='id_dia_aula',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
