# Generated by Django 4.2.4 on 2023-09-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0004_frequencia_id_dia_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='controle',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='presenca',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
