# Generated by Django 4.2.4 on 2023-09-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0005_frequencia_controle_alter_frequencia_presenca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequencia',
            name='controle',
        ),
        migrations.AddField(
            model_name='dia_aula',
            name='controle',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
