# Generated by Django 4.2.4 on 2023-09-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('professor', models.CharField(max_length=255)),
                ('dias_aulas', models.CharField(max_length=255)),
                ('obs', models.CharField(max_length=255)),
            ],
        ),
    ]
